#spring.jpa.hibernate.ddl-auto=create

spring.datasource.initialization-mode=always
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/jossdent
spring.datasource.username=postgres
spring.datasource.password=1234

server.servlet.context-path=/api
security.basic.enable: false


